export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POST = 'FETCH_POST'
export const FETCH_POST_COMMENTS = 'FETCH_POST_COMMENTS'
export const FETCH_NEWS_STORIES = 'FETCH_NEWS_STORIES'

export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_POSTS = 'FETCH_USER_POSTS'

export const RESET_USER = 'RESET_USER'
export const RESET_POST = 'RESET_POST'
export const RESET_NEWS = 'RESET_NEWS'